services:
  signaling-server:
    build: .
    container_name: vvcall-server
    ports:
      - "127.0.0.1:3030:3030"
      - "3031:3031/udp"
    volumes:
          - ./data:/app/data
    environment:
      - DATABASE_URL=/app/data/vvcall.db
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 50M
